fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: resources
      - id: trailing-whitespace
        exclude: resources
      - id: check-toml
        exclude: resources
      - id: check-yaml
        exclude: resources
      - id: fix-encoding-pragma
        exclude: resources
      - id: mixed-line-ending
        exclude: resources
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        args: [ liquid_netorks, tests]
        types: [ python ]
        pass_filenames: false
        require_serial: true
      - id: pylint
        name: pylint
        language: system
        entry: pylint
        args: [ liquid_netorks, tests ]
        types: [ python ]
        pass_filenames: false
        require_serial: true
      - id: pytest
        name: pytest
        language: system
        entry: python
        args: [ -m, pytest, tests ]
        pass_filenames: false
        require_serial: true
